#!/bin/bash
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# Run the scripts
#/usr/bin/python3.11 /home/Amibian/Desktop/DONE!!!!/Amibian/Pythons/scr_lock.py &
#/usr/bin/python3.11 /home/Amibian/Desktop/DONE!!!!/Amibian/Pythons/num_lock.py &
#/usr/bin/python3.11 /home/Amibian/Desktop/DONE!!!!/Amibian/Pythons/caps_lock.py &
# /usr/bin/python3.11 /home/Amibian/Desktop/DONE!!!!/Amibian/Pythons/usb_activity.py &

# Give root access to x server
xhost +SI:localuser:root &
