#!/bin/bash
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# set the paths to the snakepit
script_dir=$(dirname "$(readlink -f "$0")")
amibian_dir=$(dirname "$script_dir")
python_scripts_dir="$amibian_dir/Pythons"

# Run the scripts
#/usr/bin/python3.11 "$python_scripts_dir/scr_lock.py" &
#/usr/bin/python3.11 "$python_scripts_dir/num_lock.py" &
#/usr/bin/python3.11 "$python_scripts_dir/caps_lock.py" &
#/usr/bin/python3.11 "$python_scripts_dir/usb_activity.py" &

# Give root access to x server
xhost +SI:localuser:root &
