#!/bin/bash
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# This script will run on the first boot of your Raspberry Pi

# Set whiptail color scheme
export NEWT_COLORS='
root=,blue
roottext=black,white
title=white,blue
border=white,blue
textbox=black,
button=black,orange
actbutton=black,orange
compactbutton=black,
listbox=black,
actlistbox=white,blue
'

# Welcome message
whiptail --title "Welcome to Amibian" --msgbox "Hey, thank you for choosing Amibian! We will now setup your system. This may take a few minutes. Once we're done, Amibian will reboot automatically." 12 78

# Function to detect Raspberry Pi version
detect_pi_version() {
  if grep -q "Raspberry Pi 1" /proc/device-tree/model; then
    pi_version="1"
  elif grep -q "Raspberry Pi 2" /proc/device-tree/model; then
    pi_version="2"
  elif grep -q "Raspberry Pi 3" /proc/device-tree/model; then
    pi_version="3"
  elif grep -q "Raspberry Pi 4" /proc/device-tree/model; then
    pi_version="4"
  elif grep -q "Raspberry Pi 400" /proc/device-tree/model; then
    pi_version="400"
  elif grep -q "Raspberry Pi 5" /proc/device-tree/model; then
    pi_version="5"
  elif grep -q "Raspberry Pi Zero" /proc/device-tree/model; then
    pi_version="zero"
  else
    pi_version="unknown"
  fi
}

# Prompt user for Raspberry Pi version confirmation
prompt_pi_version() {
  while true; do
    if whiptail --title "Confirm Raspberry Pi Version" --yesno "It looks like you are running Amibian on a Raspberry Pi $1. Is that correct?" 10 78; then
      break
    else
      pi_version=$(whiptail --title "Select Raspberry Pi Version" --menu "Please select the correct Raspberry Pi version:" 20 78 10 \
        "zero" "Raspberry Pi Zero" \
        "1" "Raspberry Pi 1" \
        "2" "Raspberry Pi 2" \
        "3" "Raspberry Pi 3" \
        "4" "Raspberry Pi 4" \
        "400" "Raspberry Pi 400" \
        "5" "Raspberry Pi 5" \
        "500" "Raspberry Pi 500" 3>&1 1>&2 2>&3)
      if [[ $pi_version ]]; then
        break
      else
        whiptail --title "Invalid Selection" --msgbox "Please select a valid Raspberry Pi version." 8 78
      fi
    fi
  done
}

# Detect Raspberry Pi version
detect_pi_version

# Check for unsupported Raspberry Pi versions
if [[ "$pi_version" == "zero" || "$pi_version" == "0" || "$pi_version" == "1" || "$pi_version" == "2" ]]; then
  whiptail --title "Unsupported Raspberry Pi Version" --msgbox "This Raspberry Pi $pi_version is not supported. Amibian may still work, but not properly at all." 10 78
fi

# Prompt user for Pi version confirmation
if [[ "$pi_version" == "unknown" ]]; then
  whiptail --title "Unable to Detect Raspberry Pi Version" --msgbox "We couldn't detect your Raspberry Pi version automatically. Please select it from the following menu." 10 78
  pi_version=$(whiptail --title "Select Raspberry Pi Version" --menu "Please select the correct Raspberry Pi version:" 20 78 10 \
    "zero" "Raspberry Pi Zero" \
    "1" "Raspberry Pi 1" \
    "2" "Raspberry Pi 2" \
    "3" "Raspberry Pi 3" \
    "4" "Raspberry Pi 4" \
    "400" "Raspberry Pi 400" \
    "5" "Raspberry Pi 5" \
    "500" "Raspberry Pi 500" 3>&1 1>&2 2>&3)
else
  prompt_pi_version $pi_version
fi

# Copy contents based on Pi version
case $pi_version in
  "zero" | "0" | "1" ) src_dir="$HOME/base/pi1";;
  "2" ) src_dir="$HOME/base/pi2";;
  "3" ) src_dir="$HOME/base/pi3";;
  "4" | "400" ) src_dir="$HOME/base/pi4";;
  "5" | "500" ) src_dir="$HOME/base/pi5";;
esac

# Ensure destination directory exists
#dest_dir="$HOME/Amiga/Emulators/amiberry"
#mkdir -p "$dest_dir"

# Copy files from source to destination
whiptail --title "Copying Emulator" --msgbox "Copying Emulator for Raspberry Pi $pi_version to $dest_dir" 10 78
#cp -r "$src_dir/"* "$dest_dir/"

# Delete base directory and subfolders
whiptail --title "Cleanup" --msgbox "Cleaning up temporary files..." 10 78
#rm -rf "$HOME/base"

# Copy *.uae files to the configuration directory
#config_dir="$HOME/Amiga/Emulators/amiberry/conf"
#mkdir -p "$config_dir"
#whiptail --title "Copying Files" --msgbox "Copying configuration files" 10 78
#cp "$HOME/Amibian/config/"*.uae "$config_dir/"

# Run Kickstart ROM search
whiptail --title "Kickstart ROM Search" --msgbox "Running Kickstart ROM search..." 10 78
"$HOME/Amibian/shells/rom.sh" &&

# Disable this script from running again
whiptail --title "Cleanup" --msgbox "Some cleanup..." 10 78
#sudo systemctl disable first-run.service
#sudo rm /etc/systemd/system/first-run.service
#SCRIPT_PATH=$(realpath "$0")  # Get the full path of the script
#sudo rm -f "$SCRIPT_PATH"


# Expand the filesystem
whiptail --title "Expanding Filesystem" --msgbox "Expanding the file system to utilize the full SD card capacity..." 10 78
#sudo raspi-config --expand-rootfs

# Completion message and reboot
whiptail --title "Setup Complete" --msgbox "Setup completed! The system will now reboot." 10 78
#sudo reboot
exit 0
