#!/bin/bash
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# Function to find the script's directory
find_script_dir() {
    SCRIPT=$(readlink -f "$0")
    SCRIPTPATH=$(dirname "$SCRIPT")
    echo "$SCRIPTPATH"
}

# Find the root directory of the Amibian project
script_dir=$(find_script_dir)
amibian_dir=$(dirname "$script_dir")

# Create and mount the RAM disk at /mnt/ram
ramdisk_dir="/mnt/ram"
sudo mkdir -p "$ramdisk_dir"
if ! mount | grep -q "$ramdisk_dir"; then
    sudo mount -t tmpfs -o size=1000M tmpfs "$ramdisk_dir"

# Check if the RAM disk entry is already in /etc/fstab, if not, add it
fstab_entry="tmpfs   /mnt/ram  tmpfs  defaults,size=1000M  0  0"
if ! grep -q "$fstab_entry" /etc/fstab; then
    echo "$fstab_entry" | sudo tee -a /etc/fstab
fi

# Copy amibian_LED.desktop to autostart
autostart_dir="$HOME/.config/autostart"
desktop_file="$amibian_dir/desktop/amibian_LED.desktop"

# Copy ram.desktop to desktop
autostart_dir="$HOME/Desktop"
desktop_file="$amibian_dir/desktop/ram.desktop"

mkdir -p "$autostart_dir"
cp "$desktop_file" "$autostart_dir"
chmod 777 "$autostart_dir/amibian_LED.desktop"

# Copy amibian.service to systemd system directory and enable/start the service
service_file="$amibian_dir/service/amibian.service"
sudo cp "$service_file" /etc/systemd/system/
sudo systemctl enable amibian.service
sudo systemctl start amibian.service

# Set ownership of the Amibian directory and all its contents to the current user
sudo chown -R "$USER":"$USER" "$amibian_dir"

# Set permissions
chmod -R 755 "$amibian_dir/Pythons"
chmod -R 755 "$amibian_dir/shells"
find "$amibian_dir" -type f -exec chmod 644 {} \;

# Make specific file types use the Amibian script as the default app
default_app="$amibian_dir/Pythons/Amibian"
mime_types=(
    "application/x-iso9660-image"
    "application/x-cue"
    "application/zip"
    "application/x-hdf"
    "application/x-adf"
    "application/x-lha"
)

for mime_type in "${mime_types[@]}"; do
    xdg-mime default "$default_app" "$mime_type"
done

# Display a whiptail message box
whiptail --msgbox "File transfer is completed. Please open Amibian Setup and set paths to finish the installation." 8 40
