#!/bin/bash
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# Get free normal memory
ram_free=$(free -h | awk '/^Mem:/ {print $4}')

# Get GPU memory
gpu_mem=$(vcgencmd get_mem gpu | awk -F= '{print $2}')

# Convert units to MB and GB
ram_free=$(echo $ram_free | sed 's/Gi/GB/; s/Mi/MB/')
gpu_mem=$(echo $gpu_mem | sed 's/M/MB/')

# Display the results
echo "$gpu_mem graphics mem   $ram_free other mem"
