#!/bin/bash
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# This script handles copying files to the RAM disk or opening the folder

# The RAM disk directory
RAMDISK_DIR="/mnt/ram"

# If no files are passed as arguments, open the RAM disk folder
if [ "$#" -eq 0 ]; then
    thunar "$RAMDISK_DIR"
else
    # Copy each file to the RAM disk
    for file in "$@"; do
        cp -r "$file" "$RAMDISK_DIR"
    done
fi

