#!/bin/bash
# Amibian Kickstart rom finder
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# find ourselves
SCRIPT_DIR=$(dirname "$(realpath "$0")")

# find configuration file
CONFIG_FILE="$SCRIPT_DIR/../config/amibian.configuration"

# Function to log messages
log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOGFILE"
}

# does the configuration file exist ?
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: Configuration file not found at $CONFIG_FILE"
    exit 1
fi

# Extract kickstart_path from the configuration file
KICKSTART_DIR=$(grep "^kickstart_path=" "$CONFIG_FILE" | cut -d '=' -f2 | xargs)

# Check if kickstart_path is 
if [ -z "$KICKSTART_DIR" ]; then
    echo "Error: kickstart_path not defined in $CONFIG_FILE"
    exit 1
fi

# Define AMIBIAN_KICKSTART_DIR based on KICKSTART_DIR
AMIBIAN_KICKSTART_DIR="$KICKSTART_DIR/amibian"

# Log the resolved paths (for debugging purposes)
log_message "KICKSTART_DIR resolved to: $KICKSTART_DIR"
log_message "AMIBIAN_KICKSTART_DIR resolved to: $AMIBIAN_KICKSTART_DIR"

# Ensure the directories exist
if [ ! -d "$KICKSTART_DIR" ]; then
    echo "Error: KICKSTART_DIR does not exist at $KICKSTART_DIR"
    exit 1
fi

if [ ! -d "$AMIBIAN_KICKSTART_DIR" ]; then
    mkdir -p "$AMIBIAN_KICKSTART_DIR"
    log_message "Created AMIBIAN_KICKSTART_DIR at: $AMIBIAN_KICKSTART_DIR"
fi

LOGFILE="$HOME/Desktop/script_log.txt"
MOUNT_BASE="/mnt"
EXCLUDE_DIRS=("hdd" "games" "adf" "floppy" "floppie" "harddrives" "hard-drives" "hard_drives" "whdload" "whd-load" "whd_load")
STOP_SEARCH=false
DEEP_SEARCH_ACTIVE=false

# Ensure the log file exists
touch "$LOGFILE"
log_message "Script started"

# Function to find and mount USB drives
mount_usb() {
    log_message "Starting USB mount process."
    local valid_mount_points=()

    # List only removable block devices
    for dev in $(lsblk -lnpo NAME,TYPE,RM | grep "part" | grep " 1$" | awk '{print $1}'); do
        mount_point="$MOUNT_BASE/usb$(basename "$dev")"
        mkdir -p "$mount_point"

        # Attempt to mount and validate the result
        if sudo mount "$dev" "$mount_point" >> "$LOGFILE" 2>&1; then
            if [ -d "$mount_point" ]; then
                log_message "Mounted $dev at $mount_point."
                valid_mount_points+=("$mount_point")
            else
                log_message "Mount point $mount_point is not a valid directory. Skipping."
            fi
        else
            log_message "Failed to mount $dev at $mount_point. Check fstab and systemd configuration."
        fi
    done

    # Only return valid mount points
    echo "${valid_mount_points[@]}"
}

# Function to unmount USB drives and remove mount points
unmount_and_cleanup_usb() {
    for mount_point in "$@"; do
        sudo umount "$mount_point" 2>> "$LOGFILE"
        log_message "Unmounted $mount_point."
        sudo rmdir "$mount_point"
        log_message "Removed mount point $mount_point."
    done
}

# Mount the flash drive
mount_points=$(mount_usb)
if [ -z "$mount_points" ]; then
    whiptail --title "Error" --msgbox "Failed to mount the flash drive. Exiting..." 8 78
    log_message "Failed to mount flash drive. Exiting..."
    exit 1
fi
log_message "Flash drive mounted at $mount_points"

# Prompt user to search for kickstart ROMs
if (whiptail --title "Search Flash Drive" --yesno "We shall now search the flash drive for kickstart ROMs. Continue?" 8 78); then
    log_message "User chose to search for kickstart ROMs"
else
    log_message "User chose not to search for kickstart ROMs. Exiting..."
    whiptail --title "nothing done" --msgbox "Nothing done! bye" 8 78
    exit 0
fi

# Prompt user for manual or automatic mode
if (whiptail --title "Manual or Automatic" --yesno "Do you want to do this manually? 
        Do not copy other files than kickstart roms at this point.
            the file system has not been expanded yet." 8 78); then
    log_message "User chose manual mode. Opening Midnight Commander..."
    mc /mnt
    log_message "User exited Midnight Commander"
    STOP_SEARCH=true
else
    log_message "User chose automatic mode. Continuing script..."
    step=1
fi

scan_files() {
    find "$1" -maxdepth 1 -type f \( -iname "*.rom" -o -iname "*.key" -o -iname "*.bin" \) -print0
}

# Function to display files in chunks
display_files_in_chunks() {
    local files=("$@")
    local chunk_size=10
    local total_files=${#files[@]}
    local start=0

    while [ $start -lt $total_files ]; do
        local end=$((start + chunk_size))
        if [ $end -gt $total_files ]; then
            end=$total_files
        fi
        local chunk=("${files[@]:$start:$chunk_size}")
        local file_names=()
        for file in "${chunk[@]}"; do
            file_names+=("$(basename "$file")")
        done
        whiptail --title "Files Found" --msgbox "Found files:\n${file_names[*]}" 20 78
        local choice=$(whiptail --title "Copy Files" --menu "Do you want to copy these files?" 20 78 10 \
            "1" "Copy" \
            "2" "Skip" \
            "3" "Stop copying from this folder" 3>&1 1>&2 2>&3)
        
        if [ "$choice" == "1" ]; then
            for file in "${chunk[@]}"; do
                if [ -e "$KICKSTART_DIR/$(basename "$file")" ]; then
                    if (whiptail --title "File Exists" --yesno "File $(basename "$file") already exists. Overwrite?" 8 78); then
                        cp "$file" "$KICKSTART_DIR/"
                        files_copied=true
                        log_message "Copied and overwrote $file to $KICKSTART_DIR/"
                    fi
                else
                    cp "$file" "$KICKSTART_DIR/"
                    files_copied=true
                    log_message "Copied $file to $KICKSTART_DIR/"
                fi
            done
            whiptail --msgbox "Files copied to $KICKSTART_DIR/" 8 78
        elif [ "$choice" == "2" ]; then
            log_message "User chose to skip copying these files."
            start=$end
        elif [ "$choice" == "3" ]; then
            log_message "User chose to stop copying from this folder."
            break
        fi
        
        # Check if user wants to stop searching, only during deep search
        if [ "$files_copied" == "true" ] && [ "$DEEP_SEARCH_ACTIVE" == true ]; then
            if (whiptail --title "Stop Searching?" --yesno "Do you want to stop searching for files?" 8 78); then
                STOP_SEARCH=true
                log_message "User chose to stop searching during deep search."
                break
            else
                log_message "User chose to continue searching."
            fi
        fi

        start=$end
    done
}

handle_folder() {
    local folder="$1"
    log_message "Handling folder $folder"
    echo "Searching folder: $folder"

    local files=()
    while IFS= read -r -d '' file; do
        files+=("$file")
    done < <(scan_files "$folder")

    local num_files=${#files[@]}
    log_message "Found $num_files files in $folder"

    if [ $num_files -gt 0 ]; then
        if (whiptail --title "Files Found" --yesno "Found $num_files files in folder $folder. Do you want to copy files from this folder?" 12 78); then
            local choice=$(whiptail --title "Copy Options" --menu "Choose how to copy files:" 20 78 10 \
                "1" "Copy one by one" \
                "2" "Copy in chunks" \
                "3" "Copy all" \
                "4" "Skip this folder" 3>&1 1>&2 2>&3)
            
            case $choice in
                1)
                    # Copy files one by one
                    for file in "${files[@]}"; do
                        local file_choice=$(whiptail --title "Copy File" --menu "Do you want to copy file $(basename "$file")?" 20 78 10 \
                            "1" "Copy" \
                            "2" "Skip" \
                            "3" "Stop copying from this folder" 3>&1 1>&2 2>&3)
                        
                        if [ "$file_choice" == "1" ]; then
                            copy_file_with_prompt "$file"
                        elif [ "$file_choice" == "3" ]; then
                            log_message "User chose to stop copying from this folder."
                            break
                        elif [ "$file_choice" == "2" ]; then
                            log_message "User chose to skip $file."
                            continue
                        fi
                    done
                    ;;
                2)
                    display_files_in_chunks "${files[@]}"
                    ;;
                3)
                    for file in "${files[@]}"; do
                        copy_file_with_prompt "$file"
                    done
                    whiptail --msgbox "All files copied to $KICKSTART_DIR/" 8 78
                    ;;
                4)
                    log_message "User chose to skip this folder."
                    ;;
            esac
        else
            # Offer "stop searching" only during deep search when the user selects "No"
            if [ "$DEEP_SEARCH_ACTIVE" == true ]; then
                if (whiptail --title "Stop Searching?" --yesno "Do you want to stop searching for files?" 8 78); then
                    STOP_SEARCH=true
                    log_message "User chose to stop searching during deep search."
                    return
                fi
            else
                log_message "Stop searching question skipped during initial search."
            fi
        fi
    else
        log_message "No files found in folder $folder."
    fi
}

# Function to perform the initial search
initial_search() {
    log_message "Starting initial search..."
    for mount_point in $mount_points; do
        # Validate mount points silently
        if [ ! -d "$mount_point" ]; then
            continue
        fi

        log_message "Searching in $mount_point (initial search)..."
        find "$mount_point" -type d \( -iname "*amiga*" -o -iname "*roms*" -o -iname "*kickstart*" -o -iname "*cloanto*" \) ! \
            -path "*/hdd*" ! -path "*/games*" ! -path "*/adf*" ! -path "*/floppy*" ! -path "*/floppie*" ! -path "*/harddrives*" ! \
            -path "*/hard-drives*" ! -path "*/hard_drives*" ! -path "*/whdload*" ! -path "*/whd-load*" ! -path "*/whd_load*" -print0 |
        while IFS= read -r -d '' folder; do
            if [ ! -d "$folder" ]; then
                continue
            fi
            log_message "Handling folder in initial search: $folder"
            handle_folder "$folder"
        done
    done
    log_message "Initial search completed."
}

# Function to perform the deep search
deep_search() {
    log_message "Starting deep search..."
    DEEP_SEARCH_ACTIVE=true
    for mount_point in $mount_points; do
        log_message "Searching deeper in $mount_point..."
        find "$mount_point" -type d ! \
            -path "*/hdd*" ! -path "*/games*" ! -path "*/adf*" ! -path "*/floppy*" ! -path "*/floppie*" ! -path "*/harddrives*" ! \
            -path "*/hard-drives*" ! -path "*/hard_drives*" ! -path "*/whdload*" ! -path "*/whd-load*" ! -path "*/whd_load*" -print0 |
        while IFS= read -r -d '' folder; do
            if [ "$STOP_SEARCH" == true ]; then
                log_message "User requested to stop the deep search."
                break
            fi
            log_message "Handling folder in deep search: $folder"
            handle_folder "$folder"
            if [ "$STOP_SEARCH" == true ]; then
                log_message "Breaking deep search loop."
                break
            fi
        done
        if [ "$STOP_SEARCH" == true ]; then
            log_message "Breaking deep search in outer loop."
            break
        fi
    done
    DEEP_SEARCH_ACTIVE=false
    log_message "Deep search completed."
}

copy_file_with_prompt() {
    local file="$1"
    if [ -e "$KICKSTART_DIR/$(basename "$file")" ]; then
        if (whiptail --title "File Exists" --yesno "File $(basename "$file") already exists. Overwrite?" 8 78); then
            cp "$file" "$KICKSTART_DIR/"
            log_message "Copied and overwrote $file to $KICKSTART_DIR/"
        else
            log_message "Skipped copying $file due to existing file."
        fi
    else
        cp "$file" "$KICKSTART_DIR/"
        log_message "Copied $file to $KICKSTART_DIR/"
    fi
}

# Main script execution
log_message "Starting file search process..."
initial_search

# Prompt user to proceed to deep search
if (whiptail --title "Deep Search" --yesno "Initial search is done. Would you like to perform a deeper search?" 8 78); then
    deep_search
else
    log_message "User chose not to proceed with a deep search."
    whiptail --title "Search Complete" --msgbox "The search process has been completed." 8 78
fi

log_message "Checking if files were copied to KICKSTART_DIR"
if [ "$(ls -A $KICKSTART_DIR)" ]; then
    log_message "Files found in KICKSTART_DIR. Proceeding to copy specific files to AMIBIAN_KICKSTART_DIR"

    # Define file map
    declare -A file_map
    file_map=(
        ["A500-A2000kick13.rom"]="34.5 A500 a500 1.3"
        ["A1200kick31.rom"]="40.68 A1200 a1200 3.1"
        ["A4000kick31.rom"]="40.68 A4000 a4000 3.1"
        ["CD32kick31.rom"]="40.60 CD32 cd32 3.1"
        ["CD32extended.rom"]="40.60 Extend ext Extended-ROM 3.1"
    )

    for target_file in "${!file_map[@]}"; do
        markers=(${file_map[$target_file]})
        major="${markers[0]}"
        minor="${markers[1]}"
        keywords="${markers[@]:2}"


        if [[ "$target_file" == "CD32extended.rom" ]]; then
            file_to_copy=$(find "$KICKSTART_DIR" -type f -iname "*${major}*" -a -iname "*${minor}*" \( -iname "*ext*" -o -iname "*Extended-ROM*" \) | head -n 1)
        elif [[ "$target_file" == "CD32kick31.rom" ]]; then
            file_to_copy=$(find "$KICKSTART_DIR" -type f -iname "*${major}*" -a -iname "*${minor}*" \( -iname "*CD32*" -o -iname "*Kickstart*" \) | head -n 1)
        else
            file_to_copy=$(find "$KICKSTART_DIR" -type f -iname "*${major}*" -a -iname "*${minor}*" $(for keyword in ${keywords[@]}; do echo -n "-a -iname *${keyword}* "; done) | head -n 1)
        fi

        # Copy and rename if file is found
        if [ -n "$file_to_copy" ]; then
            cp "$file_to_copy" "$AMIBIAN_KICKSTART_DIR/$target_file"
            log_message "Copied $file_to_copy to $AMIBIAN_KICKSTART_DIR/$target_file"
        else
            log_message "File for $target_file not found in $KICKSTART_DIR"
        fi
    done


    rom_key_file=$(find "$KICKSTART_DIR" -type f -iname "rom.key" | head -n 1)
    if [ -n "$rom_key_file" ]; then
        cp "$rom_key_file" "$AMIBIAN_KICKSTART_DIR/"
        log_message "Copied $rom_key_file to $AMIBIAN_KICKSTART_DIR/"
    else
        log_message "rom.key file not found in $KICKSTART_DIR"
    fi

    whiptail --title "All Done" --msgbox "All done!" 8 78
else
    log_message "No files found in $KICKSTART_DIR. Exiting..."
    whiptail --title "No Files Found" --msgbox "No files were copied. All done!" 8 78
fi

# Unmount the flash drive and clean up
log_message "Unmounting flash drive and cleaning up"
unmount_and_cleanup_usb $mount_points
log_message "Flash drive unmounted and cleaned up. Script finished"
