#!/bin/bash
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# Path to the version confirmation file
script_dir=$(dirname "$(readlink -f "$0")")
amibian_dir=$(dirname "$script_dir")
version_file="$amibian_dir/config/amibian_version"
updates_applied=false

# Get the current version from the file
current_version=$(grep -oP 'amibian_\K[0-9.]*' "$version_file")

# Function to update version in the version file
update_version() {
    new_version=$1
    sed -i "s/amibian_[0-9.]*/amibian_$new_version/" "$version_file"
}

# Check and apply updates based on the current version
case "$current_version" in
    "2.0.000")
        # Tasks for version 2.0.000
        command_a
        command_b
        # Update to next version
        update_version "2.0.001"
        whiptail --msgbox "Testing function 1" 8 40
        updates_applied=true
        ;;
    "2.0.001")
        # Tasks for version 2.0.001
        command_c
        command_d
        # Update to next version
        update_version "2.0.002"
        whiptail --msgbox "Testing function 2" 8 40
        updates_applied=true
        ;;
    "2.0.002")
        # Tasks for version 2.0.002
        command_e
        command_f
        # Update to next version
        update_version "2.0.003"
        whiptail --msgbox "Testing function 3" 8 40
        updates_applied=true
        ;;
esac

# Display a message using whiptail
if $updates_applied; then
    new_version=$(grep -oP 'amibian_\K[0-9.]*' "$version_file")
    whiptail --msgbox "Updates applied. Amibian is now version $new_version" 8 40
else
    whiptail --msgbox "Amibian $current_version" 8 40
fi
