#!/usr/bin/env python3
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

import os
import sys
import time
import tkinter as tk
from tkinter import messagebox
import argparse
import subprocess
import RPi.GPIO as GPIO
import threading
import psutil
import atexit

def read_config():  # this is how we read our config file
    config = {}
    script_dir = os.path.dirname(os.path.abspath(__file__))
    config_path = os.path.join(os.path.dirname(script_dir), 'config', 'amibian.configuration')
    with open(config_path, 'r') as file:
        for line in file:
            key, value = line.strip().split('=')
            config[key] = value
    return config

config = read_config()

def led_trigger(trigger):
    global stop_thread
    if trigger == "on":
        led.ChangeDutyCycle(100)  # Set PWM to 100% duty cycle
    elif trigger == "off":
        led.ChangeDutyCycle(0)  # Set PWM to 0% duty cycle
    elif trigger == "blink":
        while not stop_thread:
            led.ChangeDutyCycle(100)
            time.sleep(0.5)
            led.ChangeDutyCycle(0)
            time.sleep(0.5)
    elif trigger == "heartbeat":
        while not stop_thread:
            led.ChangeDutyCycle(100)
            time.sleep(0.1)
            led.ChangeDutyCycle(0)
            time.sleep(0.1)
            led.ChangeDutyCycle(100)
            time.sleep(0.1)
            led.ChangeDutyCycle(0)
            time.sleep(0.7)
    elif trigger == "cpu":
        while not stop_thread:
            cpu_usage = psutil.cpu_percent(interval=1)
            if cpu_usage < 15:
                brightness = 5
            elif cpu_usage > 85:
                brightness = 100
            else:
                brightness = 5 + (cpu_usage - 15) / 70 * 95
            led.ChangeDutyCycle(brightness)
            time.sleep(1)

def clean_up_temp_file(temp_file):
    if os.path.exists(temp_file):
        os.remove(temp_file)

def generate_temp_script(file_path):
    temp_script_content = f"""#!/bin/bash
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# change to working directory
cd {config['amiberry_path']}

# start program with specific configuration
./amiberry lha "{file_path}"

# After exit, change to home directory
cd ~

# clear screen on exit
clear
"""
    temp_script_path = os.path.join('/mnt/ram', 'temp_amibian_script.sh')
    with open(temp_script_path, 'w') as temp_script_file:
        temp_script_file.write(temp_script_content)
    os.chmod(temp_script_path, 0o755)
    return temp_script_path

def run_whdload(file_path):
    global stop_thread

    try:
        # Read the LED status and GPIO pin configuration from the config file
        led_status = config.get('game_led_status', 'off')
        LED_PIN = config.get('game_led_pin', '')

        if led_status == "on" and LED_PIN:
            try:
                LED_PIN = int(LED_PIN)
                GPIO.setwarnings(False)
                GPIO.cleanup(LED_PIN)
                GPIO.setmode(GPIO.BCM)
                GPIO.setup(LED_PIN, GPIO.OUT)
                global led
                led = GPIO.PWM(LED_PIN, 1000)
                led.start(0)  # Initialize the LED with 0% duty cycle
            except ValueError:
                print("Invalid GPIO pin number. Defaulting to LED off.")
                led_status = "off"
        else:
            print("No GPIO pin configured. Defaulting to LED off.")
            led_status = "off"

        # Generate and run the temporary launcher
        temp_script_path = generate_temp_script(file_path)
        atexit.register(clean_up_temp_file, temp_script_path)
        os.chmod(temp_script_path, 0o755)

        trigger = config.get('game_led_trigger', 'off')

        if led_status == "on":
            stop_thread = False
            led_thread = threading.Thread(target=led_trigger, args=(trigger,))
            led_thread.start()

        # Close the Tkinter window before starting the subprocess
        root.destroy()

        app_process = subprocess.Popen([temp_script_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

        try:
            app_process.wait()
        except KeyboardInterrupt:
            pass
        finally:
            if led_status == "on":
                stop_thread = True
                led_thread.join()
                GPIO.output(LED_PIN, GPIO.LOW)
                GPIO.cleanup()
            clean_up_temp_file(temp_script_path)

    except Exception as e:
        print(f"Error: {e}")

    finally:
        time.sleep(1)
        print("Reset autolha.py to its original state")

def run_xarchiver(file_path):
    # Close the Tkinter window before starting the subprocess
    root.destroy()
    subprocess.Popen(['xarchiver', file_path])
    print(f"Opened file in xarchiver: {file_path}")

def on_enter(event=None):
    global choice
    choice = (choice + 1) % 3
    update_window()

def update_window():
    if choice == 0:
        label.config(text="This file will now be started in")
        image_label.config(image=whdload_img)
        bottom_label.config(text="WHDLoad")
    elif choice == 1:
        label.config(text="This file will now be opened in")
        image_label.config(image=xarchiver_img)
        bottom_label.config(text="Xarchiver")
    else:
        root.destroy()

def main(file_path):
    global root, label, image_label, bottom_label, whdload_img, xarchiver_img, choice
    choice = 0

    root = tk.Tk()
    root.title("LHA File Handler")

    label = tk.Label(root, text="This file will now be started in")
    label.pack()

    whdload_img = tk.PhotoImage(file=os.path.join(os.path.dirname(os.path.abspath(__file__)), "../graphics/misc_icons/whdload.png"))
    xarchiver_img = tk.PhotoImage(file=os.path.join(os.path.dirname(os.path.abspath(__file__)), "../graphics/misc_icons/xarchiver.png"))
    image_label = tk.Label(root, image=whdload_img)
    image_label.pack()

    bottom_label = tk.Label(root, text="WHDLoad")
    bottom_label.pack()

    root.bind('<Return>', on_enter)

    root.after(3000, root.quit)
    root.mainloop()

    if choice == 0:
        run_whdload(file_path)
    elif choice == 1:
        run_xarchiver(file_path)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="LHA File Handler")
    parser.add_argument('file_path', type=str, help='Path to the LHA file')
    args = parser.parse_args()

    file_path = os.path.abspath(args.file_path)
    main(file_path)
