#!/usr/bin/env python3
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

import sys
import os
import subprocess
import shlex
import tkinter as tk
from tkinter import PhotoImage
import RPi.GPIO as GPIO
import time
import threading
import psutil
import tempfile
import atexit

def read_config():  # this is how we read our config file
    config = {}
    script_dir = os.path.dirname(os.path.abspath(__file__))
    config_path = os.path.join(os.path.dirname(script_dir), 'config', 'amibian.configuration')
    with open(config_path, 'r') as file:
        for line in file:
            key, value = line.strip().split('=')
            config[key] = value
    return config

config = read_config()

def main():
    # Check if the script is run with a file argument
    if len(sys.argv) != 2:
        print("Usage: autorun.py <path_to_iso_or_cue_file>")
        sys.exit(1)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.abspath(sys.argv[1])
    file_ext = os.path.splitext(file_path)[1].lower()  # Get the file extension

    config_file = "amibian_cue-iso_CD32.uae"
    image_file = os.path.join(script_dir, "../graphics/misc_icons/acd32.png")
    mount_image_file = os.path.join(script_dir, "../graphics/misc_icons/mount.png")
    amiga_text = "Amiga CD32"

    # Function to mount the file
    def mount_file():
        mount_point = "/mnt/iso"
        os.makedirs(mount_point, exist_ok=True)
        command = f"sudo mount -o loop {shlex.quote(file_path)} {mount_point}"
        subprocess.run(command, shell=True)

    # Function to run the selected emulator
    def run_emulator():
        # Update the configuration file
        config_file_path = os.path.join(config['amiberry_config_path'], config_file)
        with open(config_file_path, 'r') as file:
            config_lines = file.readlines()

        with open(config_file_path, 'w') as file:
            for line in config_lines:
                if line.startswith("cdimage0="):
                    file.write(f"cdimage0={file_path}\n")
                else:
                    file.write(line)
        # Start the LED when the emulator starts
        led_thread = setup_led()
        # Run the emulator
        start_app()
        # Stop the LED thread after the emulator exits
        if led_thread:
            global stop_thread
            stop_thread = True
            led_thread.join()
        # Restore the configuration file
        with open(config_file_path, 'w') as file:
            for line in config_lines:
                if line.startswith("cdimage0="):
                    file.write("cdimage0=\n")
                else:
                    file.write(line)

    # Function to show the selection window for CUE files
    def show_selection_window_cue():
        root = tk.Tk()
        root.title("Choose Option")

        label = tk.Label(root, text="Choose an option for the CD:")
        label.pack(pady=10)

        img1 = PhotoImage(file=os.path.join(script_dir, "../graphics/misc_icons/vlc.png"))
        img2 = PhotoImage(file=os.path.join(script_dir, "../graphics/misc_icons/qmmp.png"))
        root.img1 = img1
        root.img2 = img2

        button1 = tk.Button(root, image=img1, text="Open in VLC", compound="top", command=lambda: open_in_vlc(root))
        button1.pack(side="left", padx=20, pady=20)

        button2 = tk.Button(root, image=img2, text="Open in QMMP", compound="top", command=lambda: open_in_qmmp(root))
        button2.pack(side="left", padx=20, pady=20)

        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))  # Handle window close event

        root.mainloop()

    # Function to show the selection window for ISO files
    def show_selection_window_iso():
        root = tk.Tk()
        root.title("Choose Option")

        label = tk.Label(root, text="Choose an option for the ISO:")
        label.pack(pady=10)

        img1 = PhotoImage(file=os.path.join(script_dir, "../graphics/misc_icons/vlc.png"))
        img2 = PhotoImage(file=os.path.join(script_dir, "../graphics/misc_icons/qmmp.png"))
        img3 = PhotoImage(file=os.path.join(script_dir, "../graphics/misc_icons/acd32.png"))
        img4 = PhotoImage(file=os.path.join(script_dir, "../graphics/misc_icons/mount.png"))
        root.img1 = img1
        root.img2 = img2
        root.img3 = img3
        root.img4 = img4

        button1 = tk.Button(root, image=img1, text="Open in VLC", compound="top", command=lambda: open_in_vlc(root))
        button1.pack(side="left", padx=20, pady=20)

        button2 = tk.Button(root, image=img2, text="Open in QMMP", compound="top", command=lambda: open_in_qmmp(root))
        button2.pack(side="left", padx=20, pady=20)

        button3 = tk.Button(root, image=img3, text="Run in CD32", compound="top", command=lambda: run_emulator_and_close(root))
        button3.pack(side="left", padx=20, pady=20)

        button4 = tk.Button(root, image=img4, text="Mount ISO in /mnt/iso/", compound="top", command=lambda: mount_file_and_close(root))
        button4.pack(side="left", padx=20, pady=20)

        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))

        root.mainloop()

    # Function to handle window close event
    def on_closing(root):
        global close_window_id
        if close_window_id is not None:
            root.after_cancel(close_window_id)
        if root.winfo_exists():
            root.destroy()

    # Function to open file in VLC
    def open_in_vlc(root):
        global close_window_id
        if close_window_id is not None:
            root.after_cancel(close_window_id)
        if root.winfo_exists():
            root.destroy()
        command = f"vlc {shlex.quote(file_path)}"
        subprocess.run(command, shell=True)

    # Function to open file in QMMP
    def open_in_qmmp(root):
        global close_window_id
        if close_window_id is not None:
            root.after_cancel(close_window_id)
        if root.winfo_exists():
            root.destroy()
        command = f"qmmp {shlex.quote(file_path)}"
        subprocess.run(command, shell=True)

    # Function to mount file
    def mount_file_and_close(root):
        global close_window_id
        if close_window_id is not None:
            root.after_cancel(close_window_id)
        if root.winfo_exists():
            root.destroy()
        mount_file()

    # Function to run the emulator and close the window
    def run_emulator_and_close(root):
        global close_window_id
        if close_window_id is not None:
            root.after_cancel(close_window_id)
        if root.winfo_exists():
            root.destroy()
        run_emulator()

    # Function to show the initial window for CUE files
    def show_initial_window_cue():
        root = tk.Tk()
        root.title("Amiga Emulator")

        label = tk.Label(root, text="This CD will run in")
        label.pack(pady=10)

        img = PhotoImage(file=image_file)
        img_label = tk.Label(root, image=img)
        img_label.pack(pady=10)

        text_label = tk.Label(root, text=amiga_text)
        text_label.pack(pady=10)

        change_label = tk.Label(root, text="Press Enter to change")
        change_label.pack(pady=10)

        def on_key(event):
            if event.keysym == 'Return':
                if close_window_id is not None:
                    root.after_cancel(close_window_id)
                root.destroy()
                show_selection_window_cue()

        root.bind('<Key>', on_key)

        def close_window():
            root.destroy()
            run_emulator()

        global close_window_id
        close_window_id = root.after(3000, close_window)  # Schedule close_window to run after 3 seconds

        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))  # Handle window close event

        root.mainloop()

    # Function to show the initial window for ISO files
    def show_initial_window_iso():
        root = tk.Tk()
        root.title("Mount ISO")

        label = tk.Label(root, text="This ISO will be mounted in /mnt/iso/")
        label.pack(pady=10)

        img = PhotoImage(file=mount_image_file)
        img_label = tk.Label(root, image=img)
        img_label.pack(pady=10)

        text_label = tk.Label(root, text="Press Enter to change")
        text_label.pack(pady=10)

        def on_key(event):
            if event.keysym == 'Return':
                if close_window_id is not None:
                    root.after_cancel(close_window_id)
                root.destroy()
                show_selection_window_iso()

        root.bind('<Key>', on_key)

        def close_window():
            root.destroy()
            mount_file_and_close(root)

        global close_window_id
        close_window_id = root.after(3000, close_window)  # Schedule close_window to run after 3 seconds

        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))  # Handle window close event

        root.mainloop()
        
    # Function to start the application
    def start_app():
        temp_script_content = f"""#!/bin/bash
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# change to working directory
cd {config['amiberry_path']}

# start program with specific configuration
./amiberry -f {config_file}

# After exit, change to home directory
cd ~

# clear screen on exit
clear
"""
        print("Creating temporary script...")  # Debugging statement
        temp_script_path = os.path.join('/mnt/ram', 'temp_amibian_script.sh')
        with open(temp_script_path, 'w') as temp_script_file:
            temp_script_file.write(temp_script_content)
        os.chmod(temp_script_path, 0o755)
        atexit.register(clean_up_temp_file, temp_script_path)

        app_process = subprocess.Popen([temp_script_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        print("Running temporary script...")  # Debugging statement
        try:
            app_process.wait()
        except KeyboardInterrupt:
            pass
        finally:
            clean_up_temp_file(temp_script_path)
        print("Temporary script execution completed.")  # Debugging statement
        
    def clean_up_temp_file(temp_file): #hide our tracks
        if os.path.exists(temp_file):
            os.remove(temp_file)

    # Function to clean up temporary files
    def clean_up_temp_file(temp_file):
        if os.path.exists(temp_file):
            os.remove(temp_file)

    # Function to control the LED
    def led_trigger(trigger):
        global stop_thread
        if trigger == "on":
            led.ChangeDutyCycle(100)
        elif trigger == "off":
            led.ChangeDutyCycle(0)
        elif trigger == "blink":
            while not stop_thread:
                led.ChangeDutyCycle(100)
                time.sleep(0.5)
                led.ChangeDutyCycle(0)
                time.sleep(0.5)
        elif trigger == "heartbeat":
            while not stop_thread:
                led.ChangeDutyCycle(100)
                time.sleep(0.1)
                led.ChangeDutyCycle(0)
                time.sleep(0.1)
                led.ChangeDutyCycle(100)
                time.sleep(0.1)
                led.ChangeDutyCycle(0)
                time.sleep(0.7)
        elif trigger == "cpu":
            while not stop_thread:
                cpu_usage = psutil.cpu_percent(interval=1)
                brightness = 5 + (cpu_usage - 15) / 70 * 95 if 15 <= cpu_usage <= 85 else (5 if cpu_usage < 15 else 100)
                led.ChangeDutyCycle(brightness)
                time.sleep(1)

    def start_led_thread():
        global stop_thread
        trigger = config['game_led_trigger']
        led_thread = threading.Thread(target=led_trigger, args=(trigger,))
        led_thread.start()
        return led_thread

    def setup_led():
        global led, stop_thread
        led_status = config.get('game_led_status', 'off')
        LED_PIN = config.get('game_led_pin', '')
        if led_status == "on" and LED_PIN:
            try:
                LED_PIN = int(LED_PIN)
                GPIO.setwarnings(False)
                GPIO.cleanup(LED_PIN)
                GPIO.setmode(GPIO.BCM)
                GPIO.setup(LED_PIN, GPIO.OUT)
                led = GPIO.PWM(LED_PIN, 1000)
                led.start(5)
                stop_thread = False
                return start_led_thread()
            except ValueError:
                print("Invalid GPIO pin number. Defaulting to LED off.")
                led_status = "off"
        else:
            print("No GPIO pin configured. Defaulting to LED off.")
            led_status = "off"
        return None

    global close_window_id, stop_thread
    stop_thread = False

    # Determine the file type and show the appropriate initial window
    if file_ext == ".cue":
        show_initial_window_cue()
    elif file_ext == ".iso":
        show_initial_window_iso()
    else:
        print("Unsupported file type")
        sys.exit(1)

    # Clean up the LED on exit
    if 'led' in globals() and led:
        stop_thread = True
        led_thread.join()
        GPIO.output(int(config.get('game_led_pin', 0)), GPIO.LOW)
        GPIO.cleanup()

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"Error: {e}")
