#!/usr/bin/env -S python3
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

import sys
import os
import subprocess
import shlex
import tkinter as tk
from tkinter import PhotoImage
import RPi.GPIO as GPIO
import time
import threading
import psutil
import tempfile
import atexit

def read_config():  # this is how we read our config file
    config = {}
    script_dir = os.path.dirname(os.path.abspath(__file__))
    base_path = os.path.dirname(script_dir)
    config_path = os.path.join(base_path, 'config', 'amibian.configuration')
    with open(config_path, 'r') as file:
        for line in file:
            if '=' in line:
                key, value = line.strip().split('=', 1)
                config[key] = value
    return config, base_path

def main(): #what we do
    config, base_path = read_config()

    if len(sys.argv) != 2:
        print("Usage: hdfautorun.py <path_to_hdf_file>")
        sys.exit(1)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    hdf_file = os.path.abspath(sys.argv[1])
    hdf_dir = os.path.dirname(hdf_file)

    config_file = "amibian_hdf_A1200.uae"
    image_file = os.path.join(base_path, "graphics/misc_icons/a1200.png")
    amiga_text = "Amiga 1200"

    # LED setup
    led_status = config.get('game_led_status', 'off')
    LED_PIN = config.get('game_led_pin', '')
    led_trigger_value = config.get('game_led_trigger', 'off')

    stop_thread = False
    led = None

    if led_status == "on" and LED_PIN:
        try:
            LED_PIN = int(LED_PIN)
            GPIO.setwarnings(False)  # Disable GPIO warnings
            GPIO.cleanup(LED_PIN)  # Clean up the GPIO pin before use
            GPIO.setmode(GPIO.BCM)
            GPIO.setup(LED_PIN, GPIO.OUT)
            led = GPIO.PWM(LED_PIN, 1000)
            led.start(5)
        except ValueError:
            print("Invalid GPIO pin number. Defaulting to LED off.")
            led_status = "off"
    else:
#        print("No GPIO pin configured. Defaulting to LED off.")
        led_status = "off"

    def led_trigger(trigger): # disco disco
        nonlocal stop_thread
        if trigger == "on":
            led.ChangeDutyCycle(100)
        elif trigger == "off":
            led.ChangeDutyCycle(0)
        elif trigger == "blink":
            while not stop_thread:
                led.ChangeDutyCycle(100)
                time.sleep(0.5)
                led.ChangeDutyCycle(0)
                time.sleep(0.5)
        elif trigger == "heartbeat":
            while not stop_thread:
                led.ChangeDutyCycle(100)
                time.sleep(0.1)
                led.ChangeDutyCycle(0)
                time.sleep(0.1)
                led.ChangeDutyCycle(100)
                time.sleep(0.1)
                led.ChangeDutyCycle(0)
                time.sleep(0.7)
        elif trigger == "cpu":
            while not stop_thread:
                cpu_usage = psutil.cpu_percent(interval=1)
                if cpu_usage < 15:
                    brightness = 5
                elif cpu_usage > 85:
                    brightness = 100
                else:
                    brightness = 5 + (cpu_usage - 15) / 70 * 95
                led.ChangeDutyCycle(brightness)
                time.sleep(1)

    def clean_up_temp_file(temp_file): #hide our tracks
        if os.path.exists(temp_file):
            os.remove(temp_file)

    def generate_temp_script(config_file): #because Amiberry can't easily be started with a python file
        amiberry_path = config.get('amiberry_path')
        temp_script_content = f"""#!/bin/bash
# A part of Amibian ASS. (application start system)
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# change to working directory
cd {amiberry_path}

# start program with specific configuration
./amiberry -f {config_file}

# After exit, change to home directory
cd ~

# clear screen on exit
clear
"""
        print("Creating temporary script...")  # Debugging statement
        temp_script_path = os.path.join('/mnt/ram', 'temp_amibian_script.sh')
        with open(temp_script_path, 'w') as temp_script_file:
            temp_script_file.write(temp_script_content)
        os.chmod(temp_script_path, 0o755)
        atexit.register(clean_up_temp_file, temp_script_path)

        app_process = subprocess.Popen([temp_script_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        print("Running temporary script...")  # Debugging statement
        try:
            app_process.wait()
        except KeyboardInterrupt:
            pass
        finally:
            clean_up_temp_file(temp_script_path)
        print("Temporary script execution completed.")  # Debugging statement
        
    def clean_up_temp_file(temp_file): #hide our tracks
        if os.path.exists(temp_file):
            os.remove(temp_file)

    def run_emulator(led_status, LED_PIN):
        nonlocal led, stop_thread

        if led_status == "on" and LED_PIN:
            GPIO.setwarnings(False)  # Disable GPIO warnings
            try:
                if led:
                    led.stop()  # Stop the existing PWM object
                    GPIO.cleanup(LED_PIN)  # Clean up the GPIO pin
                GPIO.setmode(GPIO.BCM)
                GPIO.setup(LED_PIN, GPIO.OUT)
                led = GPIO.PWM(LED_PIN, 1000)
                led.start(5)
                led_thread = threading.Thread(target=led_trigger, args=(led_trigger_value,))
                led_thread.start()
            except RuntimeError as e:
                print(f"Error: {e}")
                led_status = "off"

        amiberry_config_path = config.get('amiberry_config_path')
        config_file_path = os.path.join(amiberry_config_path, config_file)
        with open(config_file_path, 'r') as file:
            config_lines = file.readlines()

        original_config_lines = config_lines.copy()

        hdf_files = [os.path.join(hdf_dir, f) for f in os.listdir(hdf_dir) if f.lower().endswith('.hdf')]
        hdf_files.sort(key=lambda x: (os.path.basename(x).lower() not in ['workbench.hdf', 'system.hdf'], x))

        with open(config_file_path, 'w') as file:
            for line in original_config_lines:
                if not line.startswith("hardfile2=rw,DH") and not line.startswith("uaehf0=hdf,rw,DH"):
                    file.write(line)

            for i, hdf in enumerate(hdf_files[:7]):
                dh = f"DH{i}"
                uae = f"uae{i}"
                file.write(f"hardfile2=rw,{dh}:{hdf},32,1,2,512,0,,{uae}\n")
                file.write(f"uaehf0=hdf,rw,{dh}:{hdf},32,1,2,512,0,,{uae}\n")

        temp_script_path = generate_temp_script(config_file)
        run_temp_script(temp_script_path)

        with open(config_file_path, 'w') as file:
            file.writelines(original_config_lines)

        # Stop the LED thread and turn off the LED
        stop_thread = True
        if led:
            led.stop()
            GPIO.cleanup()

    def show_selection_window():  #info before we start
        root = tk.Tk()
        root.title("Choose Amiga")

        label = tk.Label(root, text="Which Amiga do you want to use?")
        label.pack(pady=10)

        img1 = PhotoImage(file=os.path.join(base_path, "graphics/misc_icons/a2000.png"))
        img2 = PhotoImage(file=os.path.join(base_path, "graphics/misc_icons/a4000.png"))
        root.img1 = img1
        root.img2 = img2

        button1 = tk.Button(root, image=img1, text="Amiga 2000", compound="top", command=lambda: select_emulator(root, "amibian_hdf_A2000.uae", "a2000"))
        button1.pack(side="left", padx=20, pady=20)

        button2 = tk.Button(root, image=img2, text="Amiga 4000", compound="top", command=lambda: select_emulator(root, "amibian_hdf_A4000.uae", "a4000"))
        button2.pack(side="right", padx=20, pady=20)

        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))

        def on_key(event): 
            if event.keysym == 'Return':
                root.destroy()
                sys.exit(0)

        root.bind('<Key>', on_key)
        root.mainloop()

    def on_closing(root):
        global close_window_id
        if close_window_id is not None:
            root.after_cancel(close_window_id)
        root.destroy()

    def select_emulator(root, config, selected_emulator):
        global close_window_id
        nonlocal config_file, image_file, amiga_text
        config_file = config
        image_file = os.path.join(base_path, f"graphics/misc_icons/{selected_emulator}.png")
        amiga_text = f"Amiga {selected_emulator.upper()}"
        if close_window_id is not None:
            root.after_cancel(close_window_id)
        root.destroy()
        run_emulator(led_status, LED_PIN)

    def show_initial_window():
        root = tk.Tk()
        root.title("Amiga Emulator")

        label = tk.Label(root, text="This hardfile will run in")
        label.pack(pady=10)

        img = PhotoImage(file=image_file)
        img_label = tk.Label(root, image=img)
        img_label.pack(pady=10)

        text_label = tk.Label(root, text=amiga_text)
        text_label.pack(pady=10)

        change_label = tk.Label(root, text="Press Enter to change")
        change_label.pack(pady=10)

        def on_key(event):
            if event.keysym == 'Return':
                if close_window_id is not None:
                    root.after_cancel(close_window_id)
                root.destroy()
                show_selection_window()

        root.bind('<Key>', on_key)

        def close_window():
            root.destroy()
            run_emulator(led_status, LED_PIN)

        global close_window_id
        close_window_id = root.after(3000, close_window)

        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))

        root.mainloop()

    global close_window_id
    close_window_id = None

    show_initial_window()

if __name__ == "__main__":
    main()
