#!/usr/bin/env python3
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

import sys
import os
import subprocess
import shlex
import re
import tkinter as tk
from tkinter import PhotoImage
import RPi.GPIO as GPIO
import time
import threading
import psutil
import tempfile
import atexit
from natsort import natsorted

def read_config():  # this is how we read our config file
    config = {}
    script_dir = os.path.dirname(os.path.abspath(__file__))
    config_path = os.path.join(os.path.dirname(script_dir), 'config', 'amibian.configuration')
    with open(config_path, 'r') as file:
        for line in file:
            key, value = line.strip().split('=')
            config[key] = value
    return config

config = read_config()

def main(): #what we do
    if len(sys.argv) != 2:
        print("Usage: autorun_zip.py <path_to_zip_file>")
        sys.exit(1)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    zip_file = os.path.abspath(sys.argv[1])
    zip_dir = os.path.dirname(zip_file)
    zip_basename = os.path.basename(zip_file)

    graphics_dir = os.path.join(os.path.dirname(script_dir), 'graphics/misc_icons')

    if "(AGA)" in zip_file or " AGA " in zip_file or " Aga " in zip_file or "AGA)" in zip_file or " aga " in zip_file or "(aga)" in zip_file or "(Aga)" in zip_file:
        config_file = "amibian_adf-zip_A1200.uae"
        image_file = os.path.join(graphics_dir, "a1200.png")
        amiga_text = "Amiga 1200"
        alternative_config_file = "amibian_adf-zip_A500.uae"
        alternative_image_file = os.path.join(graphics_dir, "a500.png")
        alternative_amiga_text = "Amiga 500"
    else:
        config_file = "amibian_adf-zip_A500.uae"
        image_file = os.path.join(graphics_dir, "a500.png")
        amiga_text = "Amiga 500"
        alternative_config_file = "amibian_adf-zip_A1200.uae"
        alternative_image_file = os.path.join(graphics_dir, "a1200.png")
        alternative_amiga_text = "Amiga 1200"

    def find_zip_files(zip_dir, zip_basename): #Search for more floppies
        common_substring = re.sub(r'\(.*?\)', '', zip_basename).strip()
        common_substring = re.escape(common_substring[:int(len(common_substring) * 0.6)])
        pattern = re.compile(common_substring, re.IGNORECASE)
        zip_files = [f for f in os.listdir(zip_dir) if pattern.search(f) and f.endswith('.zip')]

        if not zip_files:
            zip_files = [f for f in os.listdir(zip_dir) if f.startswith(zip_basename[:-5]) and f.endswith('.zip')]

        zip_files = natsorted(zip_files)

        return zip_files[:20]

    def led_trigger(trigger): # disco disco
        nonlocal stop_thread
        if trigger == "on":
            led.ChangeDutyCycle(100)
        elif trigger == "off":
            led.ChangeDutyCycle(0)
        elif trigger == "blink":
            while not stop_thread:
                led.ChangeDutyCycle(100)
                time.sleep(0.5)
                led.ChangeDutyCycle(0)
                time.sleep(0.5)
        elif trigger == "heartbeat":
            while not stop_thread:
                led.ChangeDutyCycle(100)
                time.sleep(0.1)
                led.ChangeDutyCycle(0)
                time.sleep(0.1)
                led.ChangeDutyCycle(100)
                time.sleep(0.1)
                led.ChangeDutyCycle(0)
                time.sleep(0.7)
        elif trigger == "cpu":
            while not stop_thread:
                cpu_usage = psutil.cpu_percent(interval=1)
                if cpu_usage < 15:
                    brightness = 5
                elif cpu_usage > 85:
                    brightness = 100
                else:
                    brightness = 5 + (cpu_usage - 15) / 70 * 95
                led.ChangeDutyCycle(brightness)
                time.sleep(1)


    def generate_and_run_temp_script(config_file):  # because Amiberry can't easily be started with a python file
        temp_script_content = f"""#!/bin/bash
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# change to working directory
cd {config['amiberry_path']}

# start program with specific configuration
./amiberry -f {config_file}

# After exit, change to home directory
cd ~

# clear screen on exit
clear
"""
        print("Creating temporary script...")  # Debugging statement
        temp_script_path = os.path.join('/mnt/ram', 'temp_amibian_script.sh')
        with open(temp_script_path, 'w') as temp_script_file:
            temp_script_file.write(temp_script_content)
        os.chmod(temp_script_path, 0o755)
        atexit.register(clean_up_temp_file, temp_script_path)

        app_process = subprocess.Popen([temp_script_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        print("Running temporary script...")  # Debugging statement
        try:
            app_process.wait()
        except KeyboardInterrupt:
            pass
        finally:
            clean_up_temp_file(temp_script_path)
        print("Temporary script execution completed.")  # Debugging statement

    def run_emulator(config_file):
        print("Starting the emulator...")  # Debugging statement
        config_file_path = os.path.join(config['amiberry_config_path'], config_file)
        with open(config_file_path, 'r') as file:
            config_lines = file.readlines()

        zip_files = find_zip_files(zip_dir, zip_basename)

        with open(config_file_path, 'w') as file:
            for line in config_lines:
                if any(line.startswith(f"floppy{i}=") for i in range(4)) or any(line.startswith(f"diskimage{i}=") for i in range(20)):
                    continue
                file.write(line)
            for i, zip in enumerate(zip_files[:4]):
                file.write(f"floppy{i}={os.path.join(zip_dir, zip)}\n")
            for i, zip in enumerate(zip_files[:20]):
                file.write(f"diskimage{i}={os.path.join(zip_dir, zip)}\n")

        generate_and_run_temp_script(config_file)
        print("Emulator started.")  # Debugging statement

    # LED setup
    led_status = config.get('game_led_status', 'off')
    LED_PIN = config.get('game_led_pin', '')
    led_trigger_value = config.get('game_led_trigger', 'off')

    stop_thread = False
    led = None

    if led_status == "on" and LED_PIN:
        GPIO.setwarnings(False)  # Disable GPIO warnings
        try:
            LED_PIN = int(LED_PIN)  # Ensure LED_PIN is an integer
            if led:
                led.stop()  # Stop the existing PWM object
                GPIO.cleanup(LED_PIN)  # Clean up the GPIO pin
            GPIO.setmode(GPIO.BCM)
            GPIO.setup(LED_PIN, GPIO.OUT)
            led = GPIO.PWM(LED_PIN, 1000)
            led.start(5)
            led_thread = threading.Thread(target=led_trigger, args=(led_trigger_value,))
            led_thread.start()
        except ValueError:
            print("Invalid GPIO pin number. Defaulting to LED off.")
            led_status = "off"
        except RuntimeError as e:
            print(f"Error: {e}")
            led_status = "off"
    else:
        led_status = "off"
        
    def clean_up_temp_file(temp_file): #hide our tracks
        if os.path.exists(temp_file):
            os.remove(temp_file)
        
    def run_xarchiver():
        command = f"xarchiver {shlex.quote(zip_file)}"
        subprocess.run(command, shell=True)

    def show_initial_window():
        root = tk.Tk()
        root.title("Amiga Emulator")

        label = tk.Label(root, text="This floppy will run in")
        label.pack(pady=10)

        img = PhotoImage(file=image_file)
        img_label = tk.Label(root, image=img)
        img_label.pack(pady=10)

        text_label = tk.Label(root, text=amiga_text)
        text_label.pack(pady=10)

        change_label = tk.Label(root, text="Press Enter to change")
        change_label.pack(pady=10)

        def on_key(event):
            if event.keysym == 'Return':
                if close_window_id is not None:
                    root.after_cancel(close_window_id)
                root.destroy()
                show_option_window()

        root.bind('<Key>', on_key)

        def close_window():
            root.destroy()
            run_emulator(config_file)
        global close_window_id
        close_window_id = root.after(3000, close_window)

        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))

        root.mainloop()

    def show_option_window():
        root = tk.Tk()
        root.title("Choose Amiga")

        label = tk.Label(root, text="Running alternative emulator")
        label.pack(pady=10)

        img = PhotoImage(file=alternative_image_file)
        img_label = tk.Label(root, image=img)
        img_label.pack(pady=10)

        text_label = tk.Label(root, text=alternative_amiga_text)
        text_label.pack(pady=10)

        def on_key(event):
            if event.keysym == 'Return':
                if close_window_id is not None:
                    root.after_cancel(close_window_id)
                root.destroy()
                run_emulator(alternative_config_file)

        root.bind('<Key>', on_key)

        def close_window():
            root.destroy()
            run_emulator(alternative_config_file)

        global close_window_id
        close_window_id = root.after(3000, close_window)

        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))
        root.mainloop()

    def show_option_window():
        root = tk.Tk()
        root.title("Choose how to open")

        label = tk.Label(root, text="Choose an option")
        label.pack(pady=10)

        frame = tk.Frame(root)
        frame.pack(pady=10)

        alt_container = tk.Frame(frame)
        alt_container.pack(side=tk.LEFT, padx=10)

        alt_img = PhotoImage(file=alternative_image_file)
        alt_button = tk.Button(alt_container, image=alt_img, command=lambda: [root.destroy(), run_emulator(alternative_config_file)])
        alt_button.pack()

        alt_text = tk.Label(alt_container, text=alternative_amiga_text)
        alt_text.pack()

        xarch_container = tk.Frame(frame)
        xarch_container.pack(side=tk.LEFT, padx=10)

        xarch_img = PhotoImage(file=os.path.join(graphics_dir, "xarchiver.png"))
        xarch_button = tk.Button(xarch_container, image=xarch_img, command=lambda: [root.destroy(), run_xarchiver()])
        xarch_button.pack()

        xarch_text = tk.Label(xarch_container, text="Xarchiver")
        xarch_text.pack()

        def on_key(event):
            if event.keysym == 'Return':
                root.destroy()
                sys.exit(0)

        root.bind('<Key>', on_key)

        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))

        root.mainloop()

    def on_closing(root):
        global close_window_id
        if close_window_id is not None:
            root.after_cancel(close_window_id)
        root.destroy()

    global close_window_id
    close_window_id = None
    show_initial_window()

if __name__ == "__main__":
    main()
