#!/usr/bin/env python3
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

import sys
import os
import subprocess
import shlex
import re
import tkinter as tk
from tkinter import PhotoImage
import RPi.GPIO as GPIO
import time
import threading
import psutil
import tempfile
import atexit
from natsort import natsorted

def read_config():  # this is how we read our config file
    config = {}
    script_dir = os.path.dirname(os.path.abspath(__file__))
    config_path = os.path.join(os.path.dirname(script_dir), 'config', 'amibian.configuration')
    with open(config_path, 'r') as file:
        for line in file:
            key, value = line.strip().split('=')
            config[key] = value
    return config

config = read_config()

def main(): #what we do
    if len(sys.argv) != 2:
        print("Usage: autorun_adf.py <path_to_adf_file>")
        sys.exit(1)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    adf_file = os.path.abspath(sys.argv[1])
    adf_dir = os.path.dirname(adf_file)
    adf_basename = os.path.basename(adf_file)

    graphics_dir = os.path.join(os.path.dirname(script_dir), 'graphics/misc_icons')

    if "(AGA)" in adf_file or " AGA " in adf_file or " Aga " in adf_file or "AGA)" in adf_file or " aga " in adf_file or "(aga)" in adf_file or "(Aga)" in adf_file:
        config_file = "adfautoa1200.uae"
        image_file = os.path.join(graphics_dir, "a1200.png")
        amiga_text = "Amiga 1200"
        alternative_config_file = "amibian_adf-zip_A500.uae"
        alternative_image_file = os.path.join(graphics_dir, "a500.png")
        alternative_amiga_text = "Amiga 500"
    else:
        config_file = "adfautoa500.uae"
        image_file = os.path.join(graphics_dir, "a500.png")
        amiga_text = "Amiga 500"
        alternative_config_file = "amibian_adf-zip_A1200.uae"
        alternative_image_file = os.path.join(graphics_dir, "a1200.png")
        alternative_amiga_text = "Amiga 1200"

    def find_adf_files(adf_dir, adf_basename):
        common_substring = re.sub(r'\(.*?\)', '', adf_basename).strip()
        common_substring = re.escape(common_substring[:int(len(common_substring) * 0.6)])
        pattern = re.compile(common_substring, re.IGNORECASE)
        adf_files = [f for f in os.listdir(adf_dir) if pattern.search(f) and f.endswith('.adf')]

        if not adf_files:
            adf_files = [f for f in os.listdir(adf_dir) if f.startswith(adf_basename[:-5]) and f.endswith('.adf')]

        adf_files = natsorted(adf_files)

        return adf_files[:20]

    def run_emulator(config_file):
        config_file_path = os.path.join(config['amiberry_config_path'], config_file)
        with open(config_file_path, 'r') as file:
            config_lines = file.readlines()

        adf_files = find_adf_files(adf_dir, adf_basename)

        with open(config_file_path, 'w') as file:
            for line in config_lines:
                if any(line.startswith(f"floppy{i}=") for i in range(4)) or any(line.startswith(f"diskimage{i}=") for i in range(20)):
                    continue
                file.write(line)
            for i, adf in enumerate(adf_files[:4]):
                file.write(f"floppy{i}={os.path.join(adf_dir, adf)}\n")
            for i, adf in enumerate(adf_files[:20]):
                file.write(f"diskimage{i}={os.path.join(adf_dir, adf)}\n")

        # Start the LED when the emulator starts
        led_thread = setup_led()

        generate_and_run_temp_script(config_file)

        with open(config_file_path, 'w') as file:
            for line in config_lines:
                if any(line.startswith(f"floppy{i}=") for i in range(4)) or any(line.startswith(f"diskimage{i}=") for i in range(20)):
                    file.write(f"{line.split('=')[0]}=\n")
                else:
                    file.write(line)

        # Stop the LED thread after the emulator exits
        if led_thread:
            global stop_thread
            stop_thread = True
            led_thread.join()


    def generate_and_run_temp_script(config_file): #because Amiberry can't easily be started with a python file
        temp_script_content = f"""#!/bin/bash
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# change to working directory
cd {config['amiberry_path']}

# start program with specific configuration
./amiberry -f {config_file}

# After exit, change to home directory
cd ~

# clear screen on exit
clear
"""
        print("Creating temporary script...")  # Debugging statement
        temp_script_path = os.path.join('/mnt/ram', 'temp_amibian_script.sh')
        with open(temp_script_path, 'w') as temp_script_file:
            temp_script_file.write(temp_script_content)
        os.chmod(temp_script_path, 0o755)
        atexit.register(clean_up_temp_file, temp_script_path)

        app_process = subprocess.Popen([temp_script_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        print("Running temporary script...")  # Debugging statement
        try:
            app_process.wait()
        except KeyboardInterrupt:
            pass
        finally:
            clean_up_temp_file(temp_script_path)
        print("Temporary script execution completed.")  # Debugging statement
        
    def clean_up_temp_file(temp_file): #hide our tracks
        if os.path.exists(temp_file):
            os.remove(temp_file)

    def led_trigger(trigger): # disco disco
        global stop_thread
        if trigger == "on":
            led.ChangeDutyCycle(100)
        elif trigger == "off":
            led.ChangeDutyCycle(0)
        elif trigger == "blink":
            while not stop_thread:
                led.ChangeDutyCycle(100)
                time.sleep(0.5)
                led.ChangeDutyCycle(0)
                time.sleep(0.5)
        elif trigger == "heartbeat":
            while not stop_thread:
                led.ChangeDutyCycle(100)
                time.sleep(0.1)
                led.ChangeDutyCycle(0)
                time.sleep(0.1)
                led.ChangeDutyCycle(100)
                time.sleep(0.1)
                led.ChangeDutyCycle(0)
                time.sleep(0.7)
        elif trigger == "cpu":
            while not stop_thread:
                cpu_usage = psutil.cpu_percent(interval=1)
                brightness = 5 + (cpu_usage - 15) / 70 * 95 if 15 <= cpu_usage <= 85 else (5 if cpu_usage < 15 else 100)
                led.ChangeDutyCycle(brightness)
                time.sleep(1)

    def start_led_thread(): #let there be light
        global stop_thread
        trigger = config['game_led_trigger']
        led_thread = threading.Thread(target=led_trigger, args=(trigger,))
        led_thread.start()
        return led_thread

    def setup_led(): #shine 
        global led, stop_thread
        led_status = config.get('game_led_status', 'off')
        LED_PIN = config.get('game_led_pin', '')

        if led_status == "on" and LED_PIN:
            try:
                LED_PIN = int(LED_PIN)
                GPIO.setmode(GPIO.BCM)
                GPIO.setup(LED_PIN, GPIO.OUT)
                led = GPIO.PWM(LED_PIN, 1000)
                led.start(5)
                stop_thread = False
                return start_led_thread()
            except ValueError:
                print("Invalid GPIO pin number. Defaulting to LED off.")
        else:
            print("No GPIO pin configured. Defaulting to LED off.")
        return None

    def show_initial_window():
        root = tk.Tk()
        root.title("Amiga Emulator")

        label = tk.Label(root, text="This floppy will run in")
        label.pack(pady=10)

        img = PhotoImage(file=image_file)
        img_label = tk.Label(root, image=img)
        img_label.pack(pady=10)

        text_label = tk.Label(root, text=amiga_text)
        text_label.pack(pady=10)

        change_label = tk.Label(root, text="Press Enter to change")
        change_label.pack(pady=10)

        def on_key(event):
            if event.keysym == 'Return':
                if close_window_id is not None:
                    root.after_cancel(close_window_id)
                root.destroy()
                show_alternative_window()

        root.bind('<Key>', on_key)

        def close_window():
            root.destroy()
            run_emulator(config_file)

        global close_window_id
        close_window_id = root.after(3000, close_window)

        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))
        root.mainloop()

    def show_alternative_window(): #incase of an mistaken identity, we can select other ways to boot the floppie
        root = tk.Tk()
        root.title("Choose Amiga")

        label = tk.Label(root, text="Running alternative emulator")
        label.pack(pady=10)

        img = PhotoImage(file=alternative_image_file)
        img_label = tk.Label(root, image=img)
        img_label.pack(pady=10)

        text_label = tk.Label(root, text=alternative_amiga_text)
        text_label.pack(pady=10)

        def on_key(event):
            if event.keysym == 'Return':
                if close_window_id is not None:
                    root.after_cancel(close_window_id)
                root.destroy()
                sys.exit(0)

        root.bind('<Key>', on_key)

        def close_window():
            root.destroy()
            run_emulator(alternative_config_file)

        global close_window_id
        close_window_id = root.after(3000, close_window)

        root.protocol("WM_DELETE_WINDOW", lambda: on_closing(root))
        root.mainloop()

    def on_closing(root):
        global close_window_id
        if close_window_id is not None:
            root.after_cancel(close_window_id)
        root.destroy()

    global close_window_id, stop_thread
    stop_thread = False
    show_initial_window()

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"Error: {e}")
