#!/usr/bin/env python3
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

import tkinter as tk
from tkinter import filedialog, messagebox
import os
import subprocess
import traceback

# Global variables to store the paths of the last created files
last_script_path = None
last_desktop_file_path = None

# Function to locate the script's directory
def get_script_dir():
    return os.path.dirname(os.path.realpath(__file__))

# Function to find the Amibian folder
def find_amibian_folder():
    script_dir = get_script_dir()
    while True:
        if os.path.basename(script_dir) == "Amibian":
            return script_dir
        parent_dir = os.path.dirname(script_dir)
        if parent_dir == script_dir:
            raise FileNotFoundError("Amibian folder not found.")
        script_dir = parent_dir

# Function to read the configuration file
def read_configuration():
    amibian_folder = find_amibian_folder()
    config_path = os.path.join(amibian_folder, "config", "amibian.configuration")
    config = {}
    with open(config_path, 'r') as file:
        for line in file:
            if '=' in line:
                key, value = line.strip().split('=', 1)
                config[key] = value
    return config

# Function to create the new launcher script
def create_launcher_script(new_script_path, executable_path, arguments):
    global last_script_path
    try:
        executable_dir = os.path.dirname(executable_path)
        executable_name = os.path.basename(executable_path)

        config = read_configuration()
        config_path = os.path.join(find_amibian_folder(), "amibian.configuration")

        script_content = repr(f'''#!/usr/bin/env python3
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

import os
import subprocess
import RPi.GPIO as GPIO
import time
import threading
import psutil
import tempfile
import atexit

def find_amibian_config():
    for root, dirs, files in os.walk('/'):
        if 'Amibian' in dirs:
            config_path = os.path.join(root, 'Amibian', 'config', 'amibian.configuration')
            if os.path.exists(config_path):
                return config_path
    raise FileNotFoundError("amibian.configuration file not found")

def read_config(config_path):
    config = {{}}
    with open(config_path, 'r') as file:
        for line in file:
            if '=' in line:
                key, value = line.strip().split('=', 1)
                config[key] = value
    return config

# Locate and read the configuration file
config_path = find_amibian_config()
config = read_config(config_path)

# Get values from the configuration file
led_status = config.get('game_led_status', 'off')
LED_PIN = int(config.get('game_led_pin', 0))
trigger = config.get('game_led_trigger', 'off')

# if led is on, then let there be light
if led_status == "on":
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(LED_PIN, GPIO.OUT)
    led = GPIO.PWM(LED_PIN, 1000)  # Increase PWM frequency to 1000 Hz
    led.start(5)  # Start PWM with 5% duty cycle

# Define a global variable to control the LED thread
stop_thread = False

# make the leds a fancy
def led_trigger(trigger):
    global stop_thread
    if trigger == "on":
        led.ChangeDutyCycle(100)  # Set PWM to 100% duty cycle
    elif trigger == "off":
        led.ChangeDutyCycle(0)  # Set PWM to 0% duty cycle
    elif trigger == "blink":
        while not stop_thread:
            led.ChangeDutyCycle(100)
            time.sleep(0.5)
            led.ChangeDutyCycle(0)
            time.sleep(0.5)
    elif trigger == "heartbeat":
        while not stop_thread:
            led.ChangeDutyCycle(100)
            time.sleep(0.1)
            led.ChangeDutyCycle(0)
            time.sleep(0.1)
            led.ChangeDutyCycle(100)
            time.sleep(0.1)
            led.ChangeDutyCycle(0)
            time.sleep(0.7)
    elif trigger == "cpu":
        while not stop_thread:
            # Get the CPU usage
            cpu_usage = psutil.cpu_percent(interval=1)
            # Scale CPU usage (15% to 85%) to LED brightness (5% to 100%)
            if cpu_usage < 15:
                brightness = 5
            elif cpu_usage > 85:
                brightness = 100
            else:
                brightness = 5 + (cpu_usage - 15) / 70 * 95
            led.ChangeDutyCycle(brightness)
            time.sleep(1)

def clean_up_temp_file(temp_file):
    if os.path.exists(temp_file):
        os.remove(temp_file)

def generate_temp_script():

    temp_script_content = f"""#!/bin/bash
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

# change to working directory
cd {executable_dir}

# start program with specific configuration
./{executable_name} {arguments}

# After exit, change to home directory
cd ~

# clear screen on exit
clear
"""
    temp_script_path = os.path.join('/mnt/ram', 'temp_amibian_script.sh')
    with open(temp_script_path, 'w') as temp_script_file:
        temp_script_file.write(temp_script_content)
    os.chmod(temp_script_path, 0o755)
    return temp_script_path

def start_app():
    global stop_thread

    # make and run the temporary launcher
    temp_script_path = generate_temp_script()
    atexit.register(clean_up_temp_file, temp_script_path)

    # Start the LED fancyness in a separate thread if LED is turned on
    if led_status == "on":
        led_thread = threading.Thread(target=led_trigger, args=(trigger,))
        led_thread.start()

    # Run the temporary launcher
    app_process = subprocess.Popen([temp_script_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    try:
        app_process.wait()
    except KeyboardInterrupt:
        pass
    finally:
        if led_status == "on":
            stop_thread = True
            led_thread.join()
            GPIO.output(LED_PIN, GPIO.LOW)
            GPIO.cleanup()
        clean_up_temp_file(temp_script_path)

if __name__ == "__main__":
    try:
        start_app()
    except Exception as e:
        print(f"Error: {{e}}")
''')

        # Replace escaped single quotes with regular single quotes
        script_content = script_content.replace("\\'", "'")
        with open(new_script_path, 'w') as file:
            for line in script_content[1:-1].split('\\n'):
                file.write(line + '\n')

        os.chmod(new_script_path, 0o755)
        last_script_path = new_script_path  # Store the path of the last created script
    except Exception as e:
        print(f"Error in create_launcher_script: {e}")
        traceback.print_exc()

# Function to create the .desktop file
def create_desktop_file(desktop_file_path, script_path, icon_path, app_name):
    global last_desktop_file_path
    try:
        desktop_content = f'''[Desktop Entry]
Type=Application
Name={app_name}
Exec=python3 {script_path}
Icon={icon_path}
Terminal=false'''
        with open(desktop_file_path, 'w') as file:
            file.write(desktop_content)
        os.chmod(desktop_file_path, 0o755)
        last_desktop_file_path = desktop_file_path  # Store the path of the last created .desktop file
    except Exception as e:
        print(f"Error in create_desktop_file: {e}")

# GUI functions using Tkinter
def select_executable():
    file_path = filedialog.askopenfilename(initialdir=os.path.expanduser("~"))
    if file_path:  # Only insert if a file was selected
        executable_entry.delete(0, tk.END)  # Clear the entry field
        executable_entry.insert(0, file_path)  # Insert the new file path
        check_executable_name(file_path)  # Check the executable name

def select_icon():
    file_path = filedialog.askopenfilename(initialdir=os.path.expanduser("~"))
    if file_path:  # Only insert if a file was selected
        icon_entry.delete(0, tk.END)  # Clear the entry field
        icon_entry.insert(0, file_path)  # Insert the new file path

def select_uae_config():
    file_path = filedialog.askopenfilename(initialdir=os.path.expanduser("~"), filetypes=[("UAE Config Files", "*.uae")])
    if file_path:  # Only insert if a file was selected
        uae_config_entry.delete(0, tk.END)  # Clear the entry field
        uae_config_entry.insert(0, file_path)  # Insert the new file path
        update_additional_arguments(file_path)  # Update additional arguments

def update_additional_arguments(config_path):
    current_args = arguments_entry.get()
    new_args = f"-f {config_path}"
    arguments_entry.delete(0, tk.END)
    arguments_entry.insert(0, new_args)

def check_executable_name(file_path):
    executable_name = os.path.basename(file_path).lower()
    if "uae4arm" in executable_name or "amiberry" in executable_name:
        uae_config_label.grid(row=3, column=0, padx=10, pady=10)
        uae_config_entry.grid(row=3, column=1, padx=10, pady=10)
        uae_config_button.grid(row=3, column=2, padx=10, pady=10)
    else:
        uae_config_label.grid_remove()
        uae_config_entry.grid_remove()
        uae_config_button.grid_remove()

# Function to hide the UAE config option
def hide_uae_config_option():
    uae_config_label.grid_remove()
    uae_config_entry.grid_remove()
    uae_config_button.grid_remove()

# Function to create the launcher
def create_launcher():
    executable_path = executable_entry.get()
    launcher_name = launcher_name_entry.get()
    icon_path = icon_entry.get()
    arguments = arguments_entry.get()

    if not launcher_name:
        messagebox.showerror("Error", "Please enter a name for the launcher.")
        return

    amibian_folder = find_amibian_folder()
    new_script_path = os.path.join(amibian_folder, 'Pythons', 'launchers', f'{launcher_name}.py')
    desktop_file_path = os.path.join(os.path.expanduser("~"), 'Desktop', f'{launcher_name}.desktop')

    # Is the directory there?
    os.makedirs(os.path.dirname(new_script_path), exist_ok=True)

    # Check if the launcher name or .desktop file is already in use
    if os.path.exists(new_script_path) or os.path.exists(desktop_file_path):
        messagebox.showerror("Error", "The launcher name or .desktop file is already in use. Please choose a different name.")
    else:
        try:
            create_launcher_script(new_script_path, executable_path, arguments)
            create_desktop_file(desktop_file_path, new_script_path, icon_path, launcher_name)
            messagebox.showinfo("Success", "Launcher created successfully!")
            clear_fields()  # Clear input fields after creating the launcher
            hide_uae_config_option()  # Hide the UAE config option
        except Exception as e:
            print(f"Error in create_launcher: {e}")
            traceback.print_exc()  # Print full traceback
            messagebox.showerror("Error", f"An error occurred: {e}")

# Function to clear input fields
def clear_fields():
    executable_entry.delete(0, tk.END)
    launcher_name_entry.delete(0, tk.END)
    icon_entry.delete(0, tk.END)
    arguments_entry.delete(0, tk.END)
    uae_config_entry.delete(0, tk.END)  # Clear the UAE config entry
    hide_uae_config_option()  # Hide the UAE config option

# Function to locate the image file
def get_image_path():
    script_dir = get_script_dir()
    return os.path.join(script_dir, '..', 'graphics', 'amibian_logo', 'Amibian.png')

# Function to cancel the last creation
def cancel_last_creation():
    global last_script_path, last_desktop_file_path
    if last_script_path or last_desktop_file_path:
        if messagebox.askyesno("Confirm Cancel", "Are you sure you want to delete the last created files?"):
            if last_script_path and os.path.exists(last_script_path):
                os.remove(last_script_path)
                last_script_path = None
            if last_desktop_file_path and os.path.exists(last_desktop_file_path):
                os.remove(last_desktop_file_path)
                last_desktop_file_path = None
            messagebox.showinfo("Cancelled", "Last created files have been deleted.")
            clear_fields()  # Clear input fields after cancellation
        else:
            messagebox.showinfo("Nothing to cancel", "Nothing has been done yet. Relax, you're good!")
    else:
        messagebox.showinfo("Nothing to cancel", "Nothing has been done yet. Relax, you're good!")

# Function to show help
def show_help():
    help_text = (
        "How to use the Amibian Launcher Creator:\n\n"
        "This creates an application launcher that turns on a gpio pin while the app you create the launcher for is running. this can be used for a led light as an exsample. you need to adjust the settings in Amibian to select to have this on or off, select what pin to use and if you want to use a led, then you can select led behaviour aswell (triggers).\n\n"
        "1. Select the executable file you want to create a launcher for.\n\n"
        "2. Enter a name for the new launcher.\n\n"
        "3. Select an icon for the launcher.\n\n"
        "4. If the executable is an Amiga emulator, choose an UAE configuration file to auto start (optional) the UAE file will be added to 'additional arguments'.\n\n"
        "5. Enter any additional arguments for the executable (optional).\n\n"
        "6. Click 'Create Launcher' to create the launcher.\n\n"
        "7. Use 'Cancel' to delete the last created launcher if needed.\n"
    )
    messagebox.showinfo("Help", help_text)

# Tkinter GUI layout
root = tk.Tk()
root.title("Amibian Launcher Creator")

# Set minimum window size
root.minsize(800, 250)

tk.Label(root, text="Select the executable:").grid(row=0, column=0, padx=10, pady=10)
executable_entry = tk.Entry(root, width=50)
executable_entry.grid(row=0, column=1, padx=10, pady=10)
tk.Button(root, text="Browse", command=select_executable).grid(row=0, column=2, padx=10, pady=10)

tk.Label(root, text="Enter the new launcher name:").grid(row=1, column=0, padx=10, pady=10)
launcher_name_entry = tk.Entry(root, width=50)
launcher_name_entry.grid(row=1, column=1, padx=10, pady=10)

tk.Label(root, text="Select an icon:").grid(row=2, column=0, padx=10, pady=10)
icon_entry = tk.Entry(root, width=50)
icon_entry.grid(row=2, column=1, padx=10, pady=10)
tk.Button(root, text="Browse", command=select_icon).grid(row=2, column=2, padx=10, pady=10)

# Add the UAE configuration option
uae_config_label = tk.Label(root, text="Select a UAE configuration to auto start (optional):")
uae_config_entry = tk.Entry(root, width=50)
uae_config_button = tk.Button(root, text="Browse", command=select_uae_config)

# Initially hide the UAE configuration option
uae_config_label.grid(row=3, column=0, padx=10, pady=10)
uae_config_entry.grid(row=3, column=1, padx=10, pady=10)
uae_config_button.grid(row=3, column=2, padx=10, pady=10)
uae_config_label.grid_remove()
uae_config_entry.grid_remove()
uae_config_button.grid_remove()

tk.Label(root, text="Enter additional arguments (Optional):").grid(row=4, column=0, padx=10, pady=10)
arguments_entry = tk.Entry(root, width=50)
arguments_entry.grid(row=4, column=1, padx=10, pady=10)

tk.Button(root, text="Create Launcher", command=create_launcher).grid(row=5, column=1, padx=10, pady=10)
tk.Button(root, text="Cancel", command=cancel_last_creation).grid(row=5, column=3, padx=10, pady=10)
tk.Button(root, text="Help", command=show_help).grid(row=5, column=2, padx=10, pady=10)
tk.Button(root, text="Exit", command=root.quit).grid(row=5, column=4, padx=10, pady=10)

# Add the image to the GUI
image_path = get_image_path()
img = tk.PhotoImage(file=image_path)
tk.Label(root, image=img).grid(row=0, column=3, rowspan=5, padx=10, pady=10)

root.mainloop()
