#!/usr/bin/env python3
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

import RPi.GPIO as GPIO
import time
import os
import re

# Function to read the configuration file
def read_config():
    config = {}
    script_dir = os.path.dirname(os.path.abspath(__file__))
    config_path = os.path.join(os.path.dirname(script_dir), 'config', 'amibian.configuration')
    with open(config_path, 'r') as file:
        for line in file:
            key, value = line.strip().split('=')
            config[key] = value
    return config

# Read the configuration
config = read_config()

# Get the Num Lock LED status and pin from the configuration
num_lock_status = config.get('numlock_led_status', 'off')
num_lock_pin = int(config.get('numlock_led_pin', '8'))

# Setup GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(num_lock_pin, GPIO.OUT)

# Function to check Num Lock status
def is_num_lock_on():
    xset_output = os.popen('xset q').read()
    match = re.search(r'Num Lock:\s+(\w+)', xset_output)
    return match and match.group(1) == 'on'

# Main loop
try:
    while True:
        if num_lock_status == 'on':
            GPIO.output(num_lock_pin, GPIO.HIGH if is_num_lock_on() else GPIO.LOW)
        else:
            GPIO.output(num_lock_pin, GPIO.LOW)
        time.sleep(0.1)
except KeyboardInterrupt:
    pass
finally:
    GPIO.cleanup()
