#!/usr/bin/env python3
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

import os
import RPi.GPIO as GPIO
import time
import threading
import psutil

def read_config():  # this is how we read our config file
    config = {}
    script_dir = os.path.dirname(os.path.abspath(__file__))
    config_path = os.path.join(os.path.dirname(script_dir), 'config', 'amibian.configuration')
    with open(config_path, 'r') as file:
        for line in file:
            key, value = line.strip().split('=')
            config[key] = value
    return config

config = read_config()

# Set up the GPIO 
LED_PIN = int(config['power_led_pin'])
GPIO.setmode(GPIO.BCM)
GPIO.setup(LED_PIN, GPIO.OUT)
led = GPIO.PWM(LED_PIN, 1000)  # Increase PWM frequency to 1000 Hz
led.start(5)  # Start PWM with 5% duty cycle

# Define a global variable to control the LED thread
stop_thread = False

# Define the trigger function
def led_trigger(trigger):
    global stop_thread
    if trigger == "on":
        led.ChangeDutyCycle(100)  # Set PWM to 100% duty cycle
    elif trigger == "off":
        led.ChangeDutyCycle(0)  # Set PWM to 0% duty cycle
    elif trigger == "blink":
        while not stop_thread:
            led.ChangeDutyCycle(100)
            time.sleep(0.5)
            led.ChangeDutyCycle(0)
            time.sleep(0.5)
    elif trigger == "heartbeat":
        while not stop_thread:
            led.ChangeDutyCycle(100)
            time.sleep(0.1)
            led.ChangeDutyCycle(0)
            time.sleep(0.1)
            led.ChangeDutyCycle(100)
            time.sleep(0.1)
            led.ChangeDutyCycle(0)
            time.sleep(0.7)
    elif trigger == "cpu":
        while not stop_thread:
            # Get the CPU usage
            cpu_usage = psutil.cpu_percent(interval=1)
            # Scale CPU usage (15% to 85%) to LED brightness (5% to 100%)
            if cpu_usage < 15:
                brightness = 5
            elif cpu_usage > 85:
                brightness = 100
            else:
                brightness = 5 + (cpu_usage - 15) / 70 * 95
            led.ChangeDutyCycle(brightness)
            time.sleep(1)

def main():
    global stop_thread

    # Get selected trigger from the configuration file
    trigger = config['power_led_trigger']

    # Start the LED trigger in a separate thread
    led_thread = threading.Thread(target=led_trigger, args=(trigger,))
    led_thread.start()

    # Run 
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        pass

    # Stop the LED thread and clean up
    stop_thread = True
    led_thread.join()
    GPIO.output(LED_PIN, GPIO.LOW)
    GPIO.cleanup()

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"Error: {e}")
