#!/usr/bin/env python3
# A part of Amibian
# Copyright © 2025 Amibian.net
# All rights reserved
# Do not edit this file.

import os
import psutil
import RPi.GPIO as GPIO
import time
import subprocess

def read_config():
    config = {}
    script_dir = os.path.dirname(os.path.abspath(__file__))
    config_path = os.path.join(os.path.dirname(script_dir), 'config', 'amibian.configuration')
    with open(config_path, 'r') as file:
        for line in file:
            key, value = line.strip().split('=')
            config[key] = value
    return config

config = read_config()

# Get GPIO pin numbers from config
usb_activity_pins = [
    config.get('usb_activity_pin1'),
    config.get('usb_activity_pin2'),
    config.get('usb_activity_pin3'),
    config.get('usb_activity_pin4')
]

# Filter out None values
usb_activity_pins = [int(pin) for pin in usb_activity_pins if pin]

if usb_activity_pins:
    # Set up GPIO
    GPIO.setmode(GPIO.BCM)
    for pin in usb_activity_pins:
        GPIO.setup(pin, GPIO.OUT)

    # Dictionary to store previous read/write counts
    previous_counts = {}
    last_activity_time = {pin: 0 for pin in usb_activity_pins}

    def get_usb_partitions():
        usb_partitions = []
        result = subprocess.run(['lsblk', '-o', 'NAME,TRAN'], stdout=subprocess.PIPE, text=True)
        lines = result.stdout.splitlines()
        for line in lines:
            parts = line.split()
            if len(parts) == 2 and parts[1] == 'usb':
                usb_partitions.append(parts[0])
        return usb_partitions

    def check_usb_activity(usb_partitions):
        activity = [False] * len(usb_activity_pins)
        io_counters = psutil.disk_io_counters(perdisk=True)

        # Check read/write activity for each USB partition
        for i, partition in enumerate(usb_partitions):
            partition_name = f"/dev/{partition}"

            if partition in io_counters:
                current_read_count = io_counters[partition].read_count
                current_write_count = io_counters[partition].write_count

                previous_read_count, previous_write_count = previous_counts.get(partition, (0, 0))

                # Detect read/write activity based on changes in counts
                if (current_read_count != previous_read_count or current_write_count != previous_write_count):
                    # Determine which pin(s) to activate
                    num_pins = len(usb_activity_pins)
                    if num_pins == 1:
                        activity[0] = True
                    elif num_pins == 2:
                        if i == 0:
                            activity[0] = True
                        elif i == 1:
                            activity[1] = True
                        elif i == 2:
                            activity[0] = activity[1] = True
                        elif i == 3:
                            activity[1] = True
                    elif num_pins == 3:
                        if i == 0:
                            activity[0] = True
                        elif i == 1:
                            activity[1] = True
                        elif i == 2:
                            activity[2] = True
                        else:
                            activity[0] = activity[1] = activity[2] = True
                    elif num_pins == 4:
                        if i < 4:
                            activity[i] = True
                        else:
                            activity[i % 4] = True

                # Update previous counts
                previous_counts[partition] = (current_read_count, current_write_count)

        return activity

    try:
        while True:
            usb_partitions = get_usb_partitions()
            activity = check_usb_activity(usb_partitions)
            current_time = time.time()
            
            for i, pin in enumerate(usb_activity_pins):
                if activity[i]:
                    last_activity_time[pin] = current_time
                    GPIO.output(pin, GPIO.HIGH)
                else:
                    if current_time - last_activity_time[pin] > 2:
                        GPIO.output(pin, GPIO.LOW)
            
            time.sleep(0.1)  # Check every 0.1 seconds
    except KeyboardInterrupt:
        pass
    finally:
        GPIO.cleanup()  # Clean up GPIO on exit
else:
    print("USB activity monitoring is disabled. No GPIO pins specified in the configuration file.")
